import { Geist, Geist_Mono } from "next/font/google";
import "./page.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "React Calculator",
  description: "Generated by Nanki Sekhon",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className= "custom-body">
        {children}
      </body>
    </html>
  );
}
